## NumPy
[NumPy](http://www.numpy.org/) is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

In [1]:
import numpy as np

In [2]:
data = np.random.rand(2, 3) # np.random.randn(2, 3)
print data
print type(data)

[[ 0.27050827  0.65552441  0.64388195]
 [ 0.71413753  0.10502647  0.91923331]]
<type 'numpy.ndarray'>


In [3]:
print data.ndim
print data.shape
print data.dtype

2
(2, 3)
float64


### Create ndarray

In [4]:
# list => ndarray
lst = range(10)
data = np.array(lst)
print data
print data.ndim
print data.shape

[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [5]:
# nested list => ndarray
lst2 = [range(10), range(10)]
data = np.array(lst2)
print data
print data.shape

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(2, 10)


* np.zeros, np.ones, np.empty

In [6]:
zeros_arr = np.zeros((3, 4))

ones_arr = np.ones((2, 3))

empty_arr = np.empty((3, 3))

empty_int_arr = np.empty((3, 3), int)

print zeros_arr
print '--------------'
print ones_arr
print '--------------'
print empty_arr
print '--------------'
print empty_int_arr

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
--------------
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
--------------
[[  4.94065646e-324   9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323   2.96439388e-323]
 [  3.45845952e-323   3.95252517e-323   4.44659081e-323]]
--------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print np.arange(10)

[0 1 2 3 4 5 6 7 8 9]


### ndarray datatypes

In [8]:
zeros_float_arr = np.zeros((3, 4), dtype=np.float64)
print zeros_float_arr
print zeros_float_arr.dtype

# astype => type transform
zeros_int_arr = zeros_float_arr.astype(np.int32)
print zeros_int_arr
print zeros_int_arr.dtype

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


### Vectorization

In [9]:
# Matrix and Matrix
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print "Element-wise multiply: "
print arr * arr

print "Matrix addition: "
print arr + arr

Element-wise multiply: 
[[ 1  4  9]
 [16 25 36]]
Matrix addition: 
[[ 2  4  6]
 [ 8 10 12]]


In [10]:
# Matrix and Scalar => Broadcasting
print 1.0 / arr
print 2.0 * arr

[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]]
[[  2.   4.   6.]
 [  8.  10.  12.]]


### Index and Slice

In [11]:
# one-dimensional
arr1 = np.arange(10)
print arr1

print arr1[2:5]

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [12]:
# multi-dimensional
arr2 = np.arange(12).reshape(3, 4)
print arr2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
print arr2[1]

print arr2[0:2, 2:]

print arr2[:, 1:3]

[4 5 6 7]
[[2 3]
 [6 7]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


* Conditional Index

In [14]:
data_arr = np.random.rand(3, 3)
print data_arr

year_arr = np.array([[2000, 2001, 2000],
                     [2005, 2002, 2009],
                     [2001, 2003, 2010]])

is_year_after_2005 = year_arr >= 2005
print is_year_after_2005, is_year_after_2005.dtype

print data_arr[is_year_after_2005]

[[ 0.24132274  0.24290864  0.40964438]
 [ 0.62237491  0.63526951  0.35180864]
 [ 0.9175882   0.1645499   0.17264982]]
[[False False False]
 [ True False  True]
 [False False  True]] bool
[ 0.62237491  0.35180864  0.17264982]


In [15]:
filtered_arr = data_arr[year_arr >= 2005]
print filtered_arr

[ 0.62237491  0.35180864  0.17264982]


In [16]:
# combined conditions
filtered_arr = data_arr[(year_arr <= 2005) & (year_arr % 2 == 0)]
print filtered_arr

[ 0.24132274  0.40964438  0.63526951]


### Transpose

In [17]:
arr = np.random.rand(2, 3)
print arr
print arr.transpose()

[[ 0.40180954  0.3614568   0.91059016]
 [ 0.49248442  0.19218862  0.55206836]]
[[ 0.40180954  0.49248442]
 [ 0.3614568   0.19218862]
 [ 0.91059016  0.55206836]]


In [18]:
arr3d = np.random.rand(2, 3, 4)
print arr3d
print '-------------------------------'
print arr3d.transpose((1, 0, 2)) # 3x2x4

[[[ 0.21037032  0.8469831   0.24278425  0.64202269]
  [ 0.54540968  0.36433457  0.10389035  0.24549166]
  [ 0.2931179   0.85763502  0.43530976  0.85923632]]

 [[ 0.28010779  0.17362656  0.8546328   0.02854199]
  [ 0.70338546  0.21264135  0.1557487   0.42192372]
  [ 0.44211358  0.33558635  0.26555935  0.58874057]]]
-------------------------------
[[[ 0.21037032  0.8469831   0.24278425  0.64202269]
  [ 0.28010779  0.17362656  0.8546328   0.02854199]]

 [[ 0.54540968  0.36433457  0.10389035  0.24549166]
  [ 0.70338546  0.21264135  0.1557487   0.42192372]]

 [[ 0.2931179   0.85763502  0.43530976  0.85923632]
  [ 0.44211358  0.33558635  0.26555935  0.58874057]]]


### Common Functions

In [19]:
arr = np.random.rand(2, 3)

print arr
print np.ceil(arr)
print np.floor(arr)
print np.rint(arr)
print np.isnan(arr)

[[ 0.11228757  0.59327282  0.93399598]
 [ 0.44392257  0.38937243  0.76498384]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  1.  1.]
 [ 0.  0.  1.]]
[[False False False]
 [False False False]]


In [20]:
arr = np.random.randn(3, 4)
print arr

print np.where(arr > 0, 1, -1)

[[-0.55997676  1.10446202 -0.31294588 -0.59142984]
 [-0.63260104  1.85153651  0.8225534   1.67989521]
 [ 0.3545866  -0.16699958 -0.32050602  0.27409438]]
[[-1  1 -1 -1]
 [-1  1  1  1]
 [ 1 -1 -1  1]]


*  Statistic Functions

In [21]:
arr = np.arange(10).reshape(5, 2)
print arr

print np.sum(arr)
print np.sum(arr, axis=0)
print np.sum(arr, axis=1)
print np.mean(arr)
print np.median(np.arange(9))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
45
[20 25]
[ 1  5  9 13 17]
4.5
4.0


* np.all, np.any

In [22]:
arr = np.random.randn(2, 3)
print arr

print np.any(arr > 0)
print np.all(arr > 0)

[[-1.10183743 -1.06473119 -0.34290519]
 [-0.78503584  0.12414087  0.588644  ]]
True
False


* np.unique

In [23]:
arr = np.array([[1, 2, 1], [2, 3, 4]])
print(arr)
print(np.unique(arr))

[[1 2 1]
 [2 3 4]]
[1 2 3 4]
